repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: python -m ruff format
        language: system
        types_or: [python, pyi]
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: python -m mypy datev_lint
        language: system
        pass_filenames: false
